### PR TITLE
Ensure maximum table name length

### PR DESCRIPTION
**Pull request by disq**
could add it in `cq-provider-sdk/provider/testing` instead maybe...

### CODE REVIEW

**Review by irmatov — APPROVED** [review]

**Review by roneli — APPROVED** [review]

**Comment by roneli** [comment]
Would suggest to add these checks in SDK will open a referencing issue, or at least verify why it didn't work there.

**Comment by disq** [comment]
@roneli not sure how to do that and keep it sane (it's a test but hang on it's not a test that's meant to run on the SDK itself... gets a provider and generates a test fn?)

Another issue, since the renamed column `image_config_repository_auth_config_repository_credentials_provider_arn` didn't exist (can't exist unless people have custom-compiled postgres with higher-limit identifiers), is the migration really needed?

**Comment by disq** [comment]
we could attempt to have a smarter the migration and try to alter column rename `image_config_repository_auth_config_repository_credentials_prov` (the cut-out column name to 63 chars) to the target column maybe?

**Comment by roneli** [comment]
> we could attempt to have a smarter the migration and try to alter column rename `image_config_repository_auth_config_repository_credentials_prov` (the cut-out column name to 63 chars) to the target column maybe?

You can try to rename on both if one exists it will just work

**Comment by roneli** [comment]
> @roneli not sure how to do that and keep it sane (it's a test but hang on it's not a test that's meant to run on the SDK itself... gets a provider and generates a test fn?)
> 
> Another issue, since the renamed column `image_config_repository_auth_config_repository_credentials_provider_arn` didn't exist (can't exist unless people have custom-compiled postgres with higher-limit identifiers), is the migration really needed?

The SDK has a feature on provider serve it will fail if table added in resource map are in valid, it does the check on runtime, there might be a bug there.

**Comment by disq** [comment]
> > we could attempt to have a smarter the migration and try to alter column rename `image_config_repository_auth_config_repository_credentials_prov` (the cut-out column name to 63 chars) to the target column maybe?
> 
> You can try to rename on both if one exists it will just work

apparently no need as it will truncate the identifier in the ALTER as well:
`NOTICE:  identifier "image_config_repository_auth_config_repository_credentials_provider_arn" will be truncated to "image_config_repository_auth_config_repository_credentials_prov"`

**Comment by disq** [comment]
SDK will need one more upgrade

**Comment by disq** [comment]
Ready to review/merge @roneli

**Review by roneli — APPROVED** [review]

**Pull request merged**
