### PR TITLE
feat: Column Resolvers   

### PR DESCRIPTION
**Pull request by bbernays**
#### Summary

2 Improvements:

1. Using the `funk.Get()` method we can completely eliminate an entire class of issues where we try and access a nil pointers. 
2. Better able to autogenerate the resolver as we don't have to check each value to see if it is nil

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests. Learn more about testing [here](https://docs.cloudquery.io/docs/developers/sdk/testing) 🧪
- [ ] Update the docs by running `go run ./docs/docs.go` and committing the changes 📃
- [ ] If adding a new resource, add [relevant Terraform files](../terraform) in a separate PR 📂
- [ ] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by yevgenypats — CHANGES_REQUESTED** [review]
I'd love to have a sync discussion but in general Im not in favour of loosing more type safety. In that case nil-deref error will stop being sent out and our permutation/mock tests also wont catch those any more.

**Review by yevgenypats — APPROVED** [review]
Revert my first comment - looks like mock tests should catch accessing wrong fields. Maybe can be improved even further with reflection/generic.

**Comment by bbernays** [comment]
This PR is now blocked by this [pr](https://github.com/cloudquery/cq-provider-sdk/pull/440)

**Review by candiduslynx — APPROVED** [review]

**Comment by candiduslynx** [comment]
I suppose the sdk needs to be updated as well

**Review by roneli — COMMENTED** [review]
Looks great, some rogue fields and linting issues, but I like this improvement

**Review by disq — APPROVED** [review]
Could update the sdk reference to be `github.com/cloudquery/cq-provider-sdk@a5db808` [a5db808](https://github.com/cloudquery/cq-provider-sdk/pull/440/commits/a5db808ca43c4934c1f273fa48e35e2eba43ecc6) to get rid of the linting errors... or just wait until a new SDK is tagged ofc

**Pull request merged**
