### PR TITLE
feat: Codepipeline webhooks

### LINKED ISSUE #658: Add support for AWS::CodePipeline::Webhook

### PR DESCRIPTION
**Pull request by zagronitay**

### CODE REVIEW

**Review by bbernays — CHANGES_REQUESTED** [review]
This PR has migrations for both `v0.10.16` and `v0.10.17`

**Review by bbernays — APPROVED** [review]

**Comment by disq** [comment]
Since `main` already has "wrong" migrations maybe merge this and open a new PR consolidating 0.16 and 0.17 migrations under 0.16.

**Review by disq — APPROVED** [review]
LGTM if sanity fetch etc. passes

**Comment by disq** [comment]
`tags` is array and not object?

**Pull request merged**
