### PR TITLE
Update EMR cluster with more info

### PR DESCRIPTION
**Pull request by irmatov**

### CODE REVIEW

**Comment by irmatov** [comment]
This will require a migration. I'm not sure how to implement it. I'm inclined to do a "DROP TABLE aws_emr_cluster" during *UP* and do nothing on *DOWN*.

What is the right way?

**Comment by roneli** [comment]
> This will require a migration. I'm not sure how to implement it. I'm inclined to do a "DROP TABLE aws_emr_cluster" during _UP_ and do nothing on _DOWN_.
> 
> What is the right way?

If you drop the table, than the table creator needs to create it on run if the user skips the build tables the resource won't work. You can do a drop -> create on the migration (you can extract the create table script from pgadmin for example)

**Comment by irmatov** [comment]
Added migrations

**Review by roneli — APPROVED** [review]
LGTM

**Pull request merged**
