### PR TITLE
Migrate AWS Golang SDK v1->v2

### PR DESCRIPTION
**Pull request by yevgenypats**
This is a migration to the new V2 aws sdk https://aws.github.io/aws-sdk-go-v2/docs/migrating/.

This should help implement solutions to the following issues and in general it will be easier to add support for more resources and enjoy all the improvements made in V2 SDK.

https://github.com/cloudquery/cloudquery/issues/59

https://github.com/cloudquery/cloudquery/issues/58

### CODE REVIEW

**Comment by yevgenypats** [comment]
@rackme @James-Quigley I've migrated AWS SDK to V2 I'd really appreciate if you can look at this or test this locally (via `./cq-provider-aws fetch`) before I merge it as it's quite a big change. This should help implement future feature requests, make the library faster and in general enjoy couple of quite good improvements in the [V2 SDK](https://aws.github.io/aws-sdk-go-v2/docs/migrating/).

**Comment by Rackme** [comment]
Currently `iam/GenerateCredentialReport` export is failing :

```
2021/02/17 15:22:59 DEBUG: Request iam/GenerateCredentialReport Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: iam.amazonaws.com
User-Agent: aws-sdk-go/1.37.5 (go1.15.8; linux; amd64)
Content-Length: 50
Authorization: AWS4-HMAC-SHA256 Credential=/20210217/us-east-1/iam/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=

Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20210217T152259Z
Accept-Encoding: gzip

2021/02/17 15:21:38 DEBUG: Response iam/GenerateCredentialReport Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 255
Content-Type: text/xml
Date: Wed, 17 Feb 2021 15:21:38 GMT
```

I will try to disable `iam.users` export and test the others.

**Comment by Rackme** [comment]
My bad this issue was for the v0.0.7 release, switching branch

**Comment by Rackme** [comment]
I got :
```
./cloudquery-aws_sdk_v2 fetch
2021-02-17T16:19:41.666Z	INFO	Calling local provider (self)
2021-02-17T16:19:41.699Z	INFO	app/provider.go:188	Creating tables if needed
2021-02-17T16:19:42.692Z	INFO	app/provider.go:271	No regions specified in config.yml. Assuming all 23 regions
2021/02/17 16:19:43 operation error CloudTrail: DescribeTrails, failed to resolve service endpoint, an AWS region is required, but was not found
```
I will try to force all regions in config.yml

**Comment by Rackme** [comment]
It seems Regions have to be declared differently now : https://aws.github.io/aws-sdk-go-v2/docs/migrating/#migrating-from-newsession-with-awsconfig-options 

V1 : 
```
sess, err := session.NewSession(aws.Config{
	Region: aws.String("us-west-2")
})
```
V2:

```
cfg, err := config.LoadDefaultConfig(context.TODO(),
	config.WithRegion("us-west-2"),
)
```

**Comment by yevgenypats** [comment]
@Rackme Thanks! I'll double test it.

**Comment by James-Quigley** [comment]
When I try to execute I get:
```
This binary is a plugin. These are not meant to be executed directly.
Please execute the program that consumes these plugins, which will
load any plugins automatically
```
I assume I need to compile slightly differently?

**Comment by yevgenypats** [comment]
@James-Quigley You actually can execute this directly by adding another command line option `fetch` (It's mainly for debug and testing purposes).

**Comment by James-Quigley** [comment]
Appears to work just fine, though I will note that I am unable to run `gen config aws`.

`Error: unknown flag: --runself`

**Comment by yevgenypats** [comment]
Cool. yes the `gen config aws` is not supported yet when running the plugin as a standalone binary. I need to add this support.

**Comment by Rackme** [comment]
If @James-Quigley has no trouble with that version, my error may be due to the fact that I am using fetch on multiple accountId.

This kind of `config.yml :`
```
accountid :
 providers:
  - name: aws
    accounts: # Optional. if you want to assume role to multiple account and fetch data from them
      - id: production
      - id: sharedstorage
      - id: test-us
      - id: test-eu
      - id: test-rds
      - id: prod-kms
      - id: uballot
      - id: mmkpm
```

**Comment by Rackme** [comment]
I pulled the Region fix and got : 

```
2021-02-17T18:12:19.172Z	INFO	ec2/subnets.go:149	Fetched resources	{"account_id": "123456123", "region": "us-east-1", "resource": "ec2.subnets", "count": 6}
2021-02-17T18:12:19.485Z	INFO	elasticbeanstalk/enironments.go:174	Fetched resources	{"account_id": "123456123", "region": "us-east-1", "resource": "elasticbeanstalk.environments", "count": 0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b63d4b]

goroutine 91 [running]:
github.com/cloudquery/cq-provider-aws/s3.(*Client).transformBucket(0xc0004cb5f0, 0xc0008b3840, 0x3d558a0, 0xc00050fec0, 0x0)
	/app/s3/buckets.go:211 +0x3eb
github.com/cloudquery/cq-provider-aws/s3.(*Client).transformBuckets(0xc0004cb5f0, 0xc00077c7e0, 0x4, 0x4, 0xc, 0xc000a4f9e0, 0x0)
	/app/s3/buckets.go:262 +0x548
github.com/cloudquery/cq-provider-aws/s3.(*Client).buckets(0xc0004cb5f0, 0x3450820, 0x0, 0x4, 0x4ded2d0)
	/app/s3/buckets.go:290 +0x16d
github.com/cloudquery/cq-provider-aws/s3.(*Client).CollectResource(0xc0004cb5f0, 0xc000941973, 0x7, 0x3450820, 0x0, 0x0, 0x0)
	/app/s3/client.go:39 +0xf6
main.(*Provider).collectResource(0xc0006ceb40, 0xc000550080, 0xc000941970, 0xa, 0x3450820, 0x0)
	/app/provider.go:367 +0x21c
created by main.(*Provider).Fetch
	/app/provider.go:318 +0x24a
```

**Comment by yevgenypats** [comment]
@Rackme fixed. It was due to a change in the API return value.

**Comment by Rackme** [comment]
Great, fixed, let's pursue with the next blocking one : 

`2021/02/17 20:46:25 operation error SNS: ListTopics, https response error StatusCode: 403, RequestID: 6b444bac-b775-553a-8ed5-120b3a958f7e, api error InvalidClientTokenId: The security token included in the request is invalid.`

**Comment by yevgenypats** [comment]
@Rackme Thanks! I believe I fixed it. I'll be merging and releasing. If there will more bumps I'll fix it after merge.

**Pull request merged**
